name: Deploy ASP.NET Core to Azure Web App

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Adjust the .NET Core version as needed

      - name: Restore dependencies
        run: dotnet restore ${{ github.workspace }}/src/Demeter.sln

      - name: Build
        run: dotnet build ${{ github.workspace }}/src/Demeter.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ github.workspace }}/src/Demeter.sln -c Release -o ${{ github.workspace }}/publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: demeter-app
          path: ${{ github.workspace }}/publish

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: demeter-app
          path: ./publish

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

      - name: Azure logout
        if: always()
        run: az logout
