name: Deploy ASP.NET Core to Azure Web App

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Adjust the .NET Core version as needed

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Restore dependencies
        run: npm run unix:restore

      - name: Build
        run: dotnet build ${{ github.workspace }}/src/Demeter.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ github.workspace }}/src/Demeter.sln -c Release -o ${{ github.workspace }}/publish --no-build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/publish

      - name: Azure logout
        if: always()
        run: az logout
